# Generated by Django 3.2.20 on 2023-08-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('title', models.CharField(default='', max_length=170)),
                ('listing_type', models.CharField(choices=[('Car', 'Car'), ('Food and Life', 'Food and Life'), ('Travelling', 'Travelling'), ('Appartements', 'Appartements'), ('Shopping', 'Shopping')], max_length=20)),
            ],
        ),
    ]
